server:
  port: 8989
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xinguan?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 111
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 111
        allow:
        deny:
        url-pattern: /druid/*
  servlet:
      multipart:
        enabled: true #是否启用http上传处理
        max-request-size: 100MB #最大请求文件的大小
        max-file-size: 20MB #设置单个文件最大长度
        file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.coderman.common.model
  configuration:
    map-underscore-to-camel-case: true
fdfs:
  resHost: https://www.zykhome.club/
  storagePort: 80
  connect-timeout: 1000
  so-timeout: 1500
  trackerList: 39.99.182.103:22122
  thumbImage:
    width: 100
    height: 100
  pool:
    max-total: 500
    max-wait-millis: 2000
alioss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4GBgYzdwbvYytAqj18Lh
  accessKeySecret: rugkelOstrBXajSbtthcq0z6geVXaj
  bucketName: xinguanwo-parent
